name: 鱼盆策略自动运行

on:
  schedule:
    - cron: '0 3 * * 1-5'  # 北京时间11:00（UTC+8）
    - cron: '0 6 * * 1-5'  # 北京时间14:00（UTC+8）
  workflow_dispatch:  # 允许手动触发

jobs:
  run-strategy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 执行策略
        run: |
          python main.py
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          WECHAT_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK }}
    
